---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: base-repository
  namespace: default
spec:
  interval: 10m
  url: oci://docker.io/garethjevans/tpb
  ref:
    tag: latest
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: config-overlay
  namespace: default
spec:
  interval: 5m
  url: https://github.com/garethjevans/bundle-controller
  ref:
    branch: main
---
apiVersion: source.garethjevans.org/v1alpha1
kind: Bundle
metadata:
  name: foo-app-source
  namespace: default
spec:
  include:
    - source:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: OCIRepository
        name: base-repository
      fromPath: .
      toPath: .
    - source:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: GitRepository
        name: config-overlay
      fromPath: overlays/production
      toPath: apps/cluster/foo/production
